# References 

1. COVID-19 World Survey Data API https://covidmap.umd.edu/api.html
2. statsmodels https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.grangercausalitytests.html
3.

In [74]:
#!pip install beautifulsoup4
#!pip install lxml

import warnings
warnings.filterwarnings(action='ignore')
import requests, bs4
import json
import pandas as pd 
import numpy as np 
import datetime as dt 
from lxml import html
import urllib 
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote
import itertools 
#
from IPython.display import clear_output

In [2]:
def retrieve_df(url_level, country="South%Korea", region="all", date="20200506"):
    # request data from api
    url_api_0 = "https://covidmap.umd.edu/api/country" # get country-level 
    url_api_1 = "https://covidmap.umd.edu/api/region" # get region-level 
    url_api_2 = f"https://covidmap.umd.edu/api/datesavail?country={country}"
    url_api_3 = f"https://covidmap.umd.edu/api/resources?indicator=covid&type=daily&country={country}&region={region}&date={date}"
    this_api = eval(f'url_api_{url_level}')
    response = requests.get(this_api, verify=False).text
    jsonData = json.loads(response)
    return jsonData['data']
    #return pd.DataFrame.from_dict(jsonData['data'])

In [3]:
def clean_list(dirty_list): 
    tlist1 = list(itertools.chain(*dirty_list)) 
    return pd.DataFrame(tlist1)

In [4]:
def gen_fb_survey(dates): 
    
    dates_len = len(dates)
    res = [] 
    q = 0
    
    for date in dates:        
        q += 1
        list_appd = retrieve_df(url_level=3, date=date)         
        res.append(list_appd)
        print(f"Write df for {date}, and {q} of {dates_len}")
        clear_output(wait=True)
    
    return clean_list(res)

In [5]:
dates =[k['survey_date'] for k in retrieve_df(2)] 
df_fb = gen_fb_survey(dates)

Write df for 20201011, and 171 of 171

In [6]:
#df
df_fb_seoul = df_fb.query('`region` == "Seoul"')

In [7]:
df_fb_seoul

,cli_se,cli_se_unw,country,gid_0,gid_1,iso_code,percent_cli,percent_cli_unw,region,sample_size,survey_date
1,0.007249,0.004662,South Korea,KOR,KOR.16_1,KOR,0.004424,0.004673,Seoul,214.0,20200503
3,0.005475,0.005218,South Korea,KOR,KOR.16_1,KOR,0.003877,0.007407,Seoul,270.0,20200504
5,0.004213,0.004962,South Korea,KOR,KOR.16_1,KOR,0.002137,0.007042,Seoul,284.0,20200505
7,0.009735,0.007092,South Korea,KOR,KOR.16_1,KOR,0.010908,0.014286,Seoul,280.0,20200506
9,0.008141,0.007067,South Korea,KOR,KOR.16_1,KOR,0.008095,0.014235,Seoul,281.0,20200507
...,...,...,...,...,...,...,...,...,...,...,...
311,0.010119,0.006472,South Korea,KOR,KOR.16_1,KOR,0.007313,0.006494,Seoul,154.0,20201004
313,0.000000,0.000000,South Korea,KOR,KOR.16_1,KOR,0.000000,0.000000,Seoul,112.0,20201005
315,0.009917,0.008583,South Korea,KOR,KOR.16_1,KOR,0.005394,0.008621,Seoul,116.0,20201006
317,0.009835,0.008439,South Korea,KOR,KOR.16_1,KOR,0.004660,0.008475,Seoul,118.0,20201007
318,0.015772,0.012296,South Korea,KOR,KOR.16_1,KOR,0.014884,0.017544,Seoul,114.0,20201009

In [8]:
def make_datestring(input_str):
    
    res1 = input_str.rjust(6, '0')
    return f"2020.{res1}".replace(".", "")

def generate_covid_seoul(start_page):
    # url 변수에 최종 완성본 url을 넣자
    end_page = start_page + 999
    url = f"http://openapi.seoul.go.kr:8088/7067764353616e6137394f68524844/json/Corona19Status/{start_page}/{end_page}"
     # url을 불러오고 이것을 인코딩을 utf-8로 전환하여 결과를 받자.
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode("utf-8")
    # 받은 데이터가 문자열이라서 이를 json으로 변환한다.
    json_object = json.loads(json_str)
    json_to_dict = json_object['Corona19Status']['row']
    tdf = pd.DataFrame.from_dict(json_to_dict)
    tdf['date_reported'] = tdf['CORONA19_DATE'].apply(make_datestring)
    
    #return url 
    return tdf.groupby(['date_reported']).size().to_frame(name = 'count').reset_index()

In [9]:
df_covid_seoul = pd.DataFrame() 

for i in range(1, 6001, 1000): 
    tdfa = generate_covid_seoul(i)
    df_covid_seoul = pd.concat([df_covid_seoul, tdfa])

In [10]:
df = pd.merge(df_fb_seoul, df_covid_seoul, how='left', left_on='survey_date', right_on='date_reported')

In [53]:
df_gc = df.query('`date_reported` == `date_reported`')
#df_gc.columns
#df_gc['cli_raw'] = df_gc['sample_size'] * df_gc['percent_cli_unw']

In [54]:
>>> import statsmodels.api as sm
>>> from statsmodels.tsa.stattools import grangercausalitytests
>>> import numpy as np

In [67]:
data1 = df_gc[["count"]].pct_change().dropna()
data2 = df_gc[["percent_cli"]].diff().dropna() 
#data3 = df_gc[["cli_raw"]].pct_change().dropna()
data = pd.concat([data1, data2], axis=1)

data

        count  percent_cli
6    0.307692     0.000099
7    0.176471    -0.001211
8   -0.400000     0.003231
9   -0.333333    -0.000752
10  -0.375000     0.000596
..        ...          ...
166  0.187500    -0.006717
167 -0.052632    -0.007313
168  0.666667     0.005394
169 -0.333333    -0.000734
170  0.250000     0.010224

[156 rows x 2 columns]

In [69]:
var = ["percent_cli", "count"]
var = ["count", "percent_cli"]
#var = ["percent_cli", "cli_raw"]
#var = ["count", "cli_raw"]
#var = ["cli_raw", "count"]
data = data[var]
data

        count  percent_cli
6    0.307692     0.000099
7    0.176471    -0.001211
8   -0.400000     0.003231
9   -0.333333    -0.000752
10  -0.375000     0.000596
..        ...          ...
166  0.187500    -0.006717
167 -0.052632    -0.007313
168  0.666667     0.005394
169 -0.333333    -0.000734
170  0.250000     0.010224

[156 rows x 2 columns]

In [70]:
gc_res = grangercausalitytests(data, 8)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0005  , p=0.9822  , df_denom=152, df_num=1
ssr based chi2 test:   chi2=0.0005  , p=0.9820  , df=1
likelihood ratio test: chi2=0.0005  , p=0.9820  , df=1
parameter F test:         F=0.0005  , p=0.9822  , df_denom=152, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0008  , p=0.9992  , df_denom=149, df_num=2
ssr based chi2 test:   chi2=0.0017  , p=0.9992  , df=2
likelihood ratio test: chi2=0.0017  , p=0.9992  , df=2
parameter F test:         F=0.0008  , p=0.9992  , df_denom=149, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.0008  , p=1.0000  , df_denom=146, df_num=3
ssr based chi2 test:   chi2=0.0024  , p=1.0000  , df=3
likelihood ratio test: chi2=0.0024  , p=1.0000  , df=3
parameter F test:         F=0.0008  , p=1.0000  , df_denom=146, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.0148  , p=0.9996  , df_denom=143, df_num=4
ssr based chi2 test:   chi2=0.0628  , p=0.9995  , df=4
likelihood ratio test: chi2=0.0628  , p=0.9995  , df=4
parameter F test:         F=0.0148  , p=0.9996  , df_denom=143, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.0431  , p=0.9989  , df_denom=140, df_num=5
ssr based chi2 test:   chi2=0.2322  , p=0.9987  , df=5
likelihood ratio test: chi2=0.2320  , p=0.9987  , df=5
parameter F test:         F=0.0431  , p=0.9989  , df_denom=140, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.2314  , p=0.9658  , df_denom=137, df_num=6
ssr based chi2 test:   chi2=1.5201  , p=0.9582  , df=6
likelihood ratio test: chi2=1.5124  , p=0.9587  , df=6
parameter F test:         F=0.2314  , p=0.9658  , df_denom=137, df_num=6

Granger Causality
number of lags (no zero) 7
ssr based F test:         F=0.3585  , p=0.9247  , df_denom=134, df_num=7
ssr based chi2 test:   chi2=2.7901  , p=0.9037  , df=7
likelihood ratio test: chi2=2.7643  , p=0.9059  , df=7
parameter F test:         F=0.3585  , p=0.9247  , df_denom=134, df_num=7

Granger Causality
number of lags (no zero) 8
ssr based F test:         F=0.3240  , p=0.9557  , df_denom=131, df_num=8
ssr based chi2 test:   chi2=2.9280  , p=0.9388  , df=8
likelihood ratio test: chi2=2.8994  , p=0.9405  , df=8
parameter F test:         F=0.3240  , p=0.9557  , df_denom=131, df_num=8

In [73]:
>>> import statsmodels.api as sm
>>> from statsmodels.tsa.stattools import grangercausalitytests
>>> import numpy as np
>>> data = sm.datasets.macrodata.load_pandas()
>>> data = data.data[["realgdp", "realcons"]].pct_change().dropna()

data = data[["realcons", "realgdp"]]

gc_res = grangercausalitytests(data, 4)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.8425  , p=0.0934  , df_denom=198, df_num=1
ssr based chi2 test:   chi2=2.8856  , p=0.0894  , df=1
likelihood ratio test: chi2=2.8650  , p=0.0905  , df=1
parameter F test:         F=2.8425  , p=0.0934  , df_denom=198, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2356  , p=0.7903  , df_denom=195, df_num=2
ssr based chi2 test:   chi2=0.4833  , p=0.7853  , df=2
likelihood ratio test: chi2=0.4827  , p=0.7856  , df=2
parameter F test:         F=0.2356  , p=0.7903  , df_denom=195, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.0546  , p=0.3696  , df_denom=192, df_num=3
ssr based chi2 test:   chi2=3.2790  , p=0.3506  , df=3
likelihood ratio test: chi2=3.2523  , p=0.3543  , df=3
parameter F test:         F=1.0546  , p=0.3696  , df_denom=192, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3047  , p=0.2698  , df_denom=189, df_num=4
ssr based chi2 test:   chi2=5.4671  , p=0.2426  , df=4
likelihood ratio test: chi2=5.3930  , p=0.2493  , df=4
parameter F test:         F=1.3047  , p=0.2698  , df_denom=189, df_num=4

In [ ]:
import matplotlib.pyplot as plt 
plt.rcParams["figure.figsize"] = (20,8)

In [ ]:
df_fig = df_seoul
fig, ax = plt.subplots(1)
ax.plot(df_fig['survey_date'], df_fig['percent_cli'])
ax.set_xticklabels([])

plt.show()

In [ ]:
import urllib.request

## data.go.kr api 
basic_url = 'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson?serviceKey='
my_api_key = 'M3jBsz%2FCY6CB9tMYmAf9SQ8AMW6AtjQDjshDbBlpsTadmBOfyBTVoYSqAvMVX5HH2GNgM%2FzOHv150PFIyQbkig%3D%3D'
options = '&pageNo=1&numOfRows=10&startCreateDt=20200310&endCreateDt=20200315'

url_combined = f'{basic_url}{my_api_key}{options}'

response = urllib.request.urlopen(url_combined)
xml_str = response.read().decode("utf-8")

In [ ]:
# 1. URL 파라미터 분리하기.
# Service URL
xmlUrl = 'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson'
My_API_Key = unquote('M3jBsz%2FCY6CB9tMYmAf9SQ8AMW6AtjQDjshDbBlpsTadmBOfyBTVoYSqAvMVX5HH2GNgM%2FzOHv150PFIyQbkig%3D%3D')    # 아래 내가 받은 인증키가 안 되서 수업용 인증키 사용.
# My_API_Key = unquote('Agq7hySmyMi1FFU9kYibP%2BEnxYepQ%2FB6Dn%2Bw9lsYKVSCDjTwIdvpjmuhJrtyQrhipg3F3a4jbSq%2FLxHi%2FdUIoQ%3D%3D')    # 사용자 인증키
queryParams = '?' + urlencode(    # get 방식으로 쿼리를 분리하기 위해 '?'를 넣은 것이다. 메타코드 아님.
    {
        quote_plus('ServiceKey') : My_API_Key,    # 필수 항목 1 : 서비스키 (본인의 서비스키)
        quote_plus('startCreateDt') : '20200310',          # 필수 항목 2 : 지역코드 (법정코드목록조회에서 확인)
        quote_plus('endCreateDt') : '20200315'         # 픽수 항목 3 : 계약월
     }
)

response = requests.get(xmlUrl + queryParams).text.encode('utf-8')
xmlobj = bs4.BeautifulSoup(response, "html.parser")

In [ ]:
rows = xmlobj.findAll('item')
rows[0]

In [ ]:
rowList = []
nameList = []
columnList = []

rowsLen = len(rows)
for i in range(0, rowsLen):
    columns = rows[i].find_all()
    
    columnsLen = len(columns)
    for j in range(0, columnsLen):
        # 첫 번째 행 데이터 값 수집 시에만 컬럼 값을 저장한다. (어차피 rows[0], rows[1], ... 모두 컬럼헤더는 동일한 값을 가지기 때문에 매번 반복할 필요가 없다.)
        if i == 0:
            nameList.append(columns[j].name)
        # 컬럼값은 모든 행의 값을 저장해야한다.    
        eachColumn = columns[j].text
        columnList.append(eachColumn)
    rowList.append(columnList)
    columnList = []    # 다음 row의 값을 넣기 위해 비워준다. (매우 중요!!)
    
result = pd.DataFrame(rowList, columns=nameList)
result.head()

In [ ]:
tdf[-100:]

In [ ]:
tdf